config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pictures
  root "pictures#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy]

  def index
    @pics = Picture.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pic = current_user.pictures.build
  end

  def create
    @pic = current_user.pictures.build(pic_params)
    if @pic.save
      flash[:success] = "Yaye! Your picture is posted!"
      redirect_to @pic
    else
      render "new"
    end
  end

  def edit

  end

  def update
    if @pic.update(pic_params)
      flash[:success] = "Your picture was updated"
      redirect_to @pic
    else
      render "edit"
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  private

  def pic_params
    params.require(:picture).permit(:title, :description)
  end

  def find_pic
    @pic = Picture.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav navbar navbar-inverse">
      <div class="container">
        <div class="navbar-brand"><%= link_to "Instagram", root_path %>
        </div>

          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-left">
            <li> <%= link_to "Upload your picture", new_picture_path %></li>
            <li> <%= link_to "Settings", edit_user_registration_path %></li>
            <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Join Instagram now", new_user_registration_path%> </li>
            <li><%= link_to "Log in", new_user_session_path%></li>

          <% end %>

      </div>
    </div>

    <div class="container">

      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>

    </div>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= simple_form_for @pic, html: {multipart: true} do |f| %>
<% if @pic.errors.any? %>

  <h2> <%= pluralize(@pic.errors.count, "error") %> prevented this Picture from saving </h2>
  <ul>
    <% @pic.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
  <% end %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.button :submit, class: "btn btn-info" %>
  <% end %>

app/views/pictures/edit.html.erb
<h1>Update Picture</h1>
<%= render "form" %>
<%= link_to "Cancel", picture_path %>

app/views/pictures/index.html.erb
<% @pics.each do |pic| %>
  <h2><%= link_to pic.title, picture_path(pic) %></h2>
  <p><%= time_ago_in_words(pic.created_at) %> ago </p>
<% end %>

<%= link_to "Upload a new picture", new_picture_path %>

app/views/pictures/new.html.erb
<h1> Post Pic </h1>

  <%= render "form" %>
  <%= link_to "Back", root_path %>

app/views/pictures/show.html.erb
<h1> <%= @pic.title %> </h1>
<p> <%= @pic.description %> </p>
<p> Posted by <%= @pic.user.email %> </p>
<br>
<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_picture_path %>
<%= link_to "Delete", picture_path, method: :delete, data: { confirm: "Are you sure?" }  %>